### ISSUE TITLE
[BUG] Certificate invalid for ui.discordtickets.app

### ISSUE THREAD

**Issue by Seblor** [discord-tickets/discord.svelte#1]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The HTTPS certificate for [ui.discordtickets.app](https://ui.discordtickets.app/) is invalid, and since the .app TLD uses HSTS, it can only be visited with HTTPS.

**Comment by eartharoid** [comment]
ui.discordtickets.app doesn't exist because this repository hasn't gone further than being generated from a template.
You might want to try https://github.com/skyra-project/discord-components.
